# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, max_length=10)),
                ('course', models.CharField(blank=True, max_length=10)),
                ('period', models.CharField(blank=True, max_length=10)),
                ('year1', models.IntegerField(blank=True)),
                ('year2', models.IntegerField(blank=True)),
                ('year3', models.IntegerField(blank=True)),
                ('year4', models.IntegerField(blank=True)),
                ('room1', models.CharField(blank=True, max_length=10)),
                ('room2', models.CharField(blank=True, max_length=10)),
                ('room3', models.CharField(blank=True, max_length=10)),
                ('room4', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
