# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=True)),
                ('course', models.CharField(blank=True, max_length=10)),
                ('year1', models.CharField(blank=True, max_length=10)),
                ('year2', models.CharField(blank=True, max_length=10)),
                ('year3', models.CharField(blank=True, max_length=10)),
                ('year4', models.CharField(blank=True, max_length=10)),
                ('period', models.CharField(blank=True, max_length=10)),
                ('room', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
