# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='unit1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='unit2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='unit3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='unit4',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
