# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablerapp', '0003_auto_20180706_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
