# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablerapp', '0006_auto_20180708_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
