# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablerapp', '0008_auto_20180709_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
