# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablerapp', '0010_auto_20180709_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablerapp.Lecturer'),
        ),
        migrations.AlterField(
            model_name='assign',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablerapp.Unit'),
        ),
    ]
