# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablerapp', '0011_auto_20180709_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assign',
            name='lecturer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assign',
            name='unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
